name: Build LaTeX document
on:
  push:
  pull_request:
    branches:
    - main
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Cache LaTeX
        id: cache-latex
        uses: actions/cache@v4
        with:
          path: /usr/share/texlive/
          key: texlive        
      - name: Install LaTeX dependencies
        if: steps.cache-latex.outputs.cache-hit != 'true'
        run: |
          sudo apt-get update
          sudo xargs -a requirements.txt sudo apt install -y
      - name: Compile LaTeX document
        run: |
          pdflatex cv.tex
      - uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: cv.pdf
