name: Build LaTeX document
on:
  push:
  pull_request:
    branches:
    - main
  release:
      types: [published]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Cache LaTeX
        id: cache-latex
        uses: actions/cache@v4
        with:
          path: |
            /usr/share/texlive/        
          key: texlive   
      - name: Update Package Index
        run: |
          sudo apt-get update           
      - name: Install LaTeX dependencies
        run: |          
          sudo xargs -a requirements.txt sudo apt install -y
      - name: Compile LaTeX document
        run: |
          pdflatex cv.tex
      - uses: actions/upload-artifact@v4
        with:
          name: cv
          path: cv.pdf
          compression-level: 0
